### ISSUE TITLE
Missing concrete implementations when building using Flutter 3.22

### ISSUE THREAD

**Issue by hjiangsu** [deakjahn/l10n_esperanto#10]
Thanks for making this package! I just wanted to point out some issues with missing implementations when building with Flutter 3.22 which was released a few days ago.

Building an app using Flutter 3.22 and `l10n_esperanto` fails due to missing implementations for two new strings. In particular, these are the missing implementations:
- `MaterialLocalizations.clearButtonTooltip`
- `MaterialLocalizations.selectedDateLabel`

To reproduce, upgrade to Flutter 3.22 and observe errors:
```
Missing concrete implementations of 'getter MaterialLocalizations.clearButtonTooltip' and 'getter MaterialLocalizations.selectedDateLabel'.
Try implementing the missing methods, or make the class abstract.
```

**Comment by deakjahn** [comment]
2.0.11 published.
