### ISSUE TITLE
Build error with Flutter 3.27.0

### ISSUE THREAD

**Issue by casimir** [deakjahn/l10n_esperanto#11]
Hi there, first of all thanks for this package!

Yesterday I started to see failling CI while building with the latest Flutter version. Really latest since the version with an issue (3.27.0) was deployed yesterday.

The error is as follow:
```
../../.pub-cache/hosted/pub.dev/l10n_esperanto-2.0.11/lib/src/cupertino.dart:18:9: Error: The implicitly called unnamed constructor from 'GlobalCupertinoLocalizations' has required parameters.
Try adding an explicit super initializer with the required arguments.
  const CupertinoLocalizationsEo({
  ```

After some poking I found out that the new parameter is `super.weekDayFormat`. I am not sure of the handle the retro-compatibility correctly so here is an issue instead of a PR.

In the meantine, I have made an ugly workaround for now, hope this help: https://github.com/casimir/frigoligo/commit/971308f03a8b5fc459bba47a7cd5e9c23f05f548#diff-f9cd02bd3b1f8a7d4fea148a6bb622cf86720f2e0c6d1c98f940a5e0c7f11235R1-R4

**Comment by deakjahn** [comment]
Thanks. In theory, specyfing the minimum SDK in the pubspec should take care of the backward compatibility, let's hope so.

**Comment by casimir** [comment]
Works perfectly in my case. Thanks again.
