### ISSUE TITLE
Missing implementations error

### ISSUE THREAD

**Issue by 12people** [deakjahn/l10n_esperanto#2]
This fails in the latest version of Flutter with this error:
 

> Error: The non-abstract class 'MaterialLocalizationsEo' is missing implementations for these members:
> ../…/lib/l10n_esperanto.dart:12
>  - MaterialLocalizations.keyboardKeyAlt
>  - MaterialLocalizations.keyboardKeyAltGraph
>  - MaterialLocalizations.keyboardKeyBackspace
> 
>  - MaterialLocalizations.keyboardKeyCapsLock
>  - MaterialLocalizations.keyboardKeyChannelDown
>  - MaterialLocalizations.keyboardKeyChannelUp
>  - MaterialLocalizations.keyboardKeyControl
>  - MaterialLocalizations.keyboardKeyDelete
>  - MaterialLocalizations.keyboardKeyEject
>  - MaterialLocalizations.keyboardKeyEnd
>  - MaterialLocalizations.keyboardKeyEscape
>  - MaterialLocalizations.keyboardKeyFn
>  - MaterialLocalizations.keyboardKeyHome
>  - MaterialLocalizations.keyboardKeyInsert
>  - MaterialLocalizations.keyboardKeyMeta
>  - MaterialLocalizations.keyboardKeyMetaMacOs
>  - MaterialLocalizations.keyboardKeyMetaWindows
>  - MaterialLocalizations.keyboardKeyNumLock
>  - MaterialLocalizations.keyboardKeyNumpad0
>  - MaterialLocalizations.keyboardKeyNumpad1
>  - MaterialLocalizations.keyboardKeyNumpad2
>  - MaterialLocalizations.keyboardKeyNumpad3
>  - MaterialLocalizations.keyboardKeyNumpad4
>  - MaterialLocalizations.keyboardKeyNumpad5
>  - MaterialLocalizations.keyboardKeyNumpad6
>  - MaterialLocalizations.keyboardKeyNumpad7
>  - MaterialLocalizations.keyboardKeyNumpad8
>  - MaterialLocalizations.keyboardKeyNumpad9
>  - MaterialLocalizations.keyboardKeyNumpadAdd
>  - MaterialLocalizations.keyboardKeyNumpadComma
>  - MaterialLocalizations.keyboardKeyNumpadDecimal
>  - MaterialLocalizations.keyboardKeyNumpadDivide
>  - MaterialLocalizations.keyboardKeyNumpadEnter
>  - MaterialLocalizations.keyboardKeyNumpadEqual
>  - MaterialLocalizations.keyboardKeyNumpadMultiply
>  - MaterialLocalizations.keyboardKeyNumpadParenLeft
>  - MaterialLocalizations.keyboardKeyNumpadParenRight
>  - MaterialLocalizations.keyboardKeyNumpadSubtract
>  - MaterialLocalizations.keyboardKeyPageDown
>  - MaterialLocalizations.keyboardKeyPageUp
>  - MaterialLocalizations.keyboardKeyPower
>  - MaterialLocalizations.keyboardKeyPowerOff
>  - MaterialLocalizations.keyboardKeyPrintScreen
>  - MaterialLocalizations.keyboardKeyScrollLock
>  - MaterialLocalizations.keyboardKeySelect
>  - MaterialLocalizations.keyboardKeySpace
>  - MaterialLocalizations.menuBarMenuLabel

**Comment by deakjahn** [comment]
Thanks. Added and published with https://github.com/deakjahn/l10n_esperanto/commit/5691291466e162b0f26f06fd99113b031f3bb4fa .

**Comment by 12people** [comment]
Great, thanks for the lightning fast response!
