### ISSUE TITLE
Missing / soon to be missing implementations

### ISSUE THREAD

**Issue by florian-obernberger** [deakjahn/l10n_esperanto#7]
First of: Thank you so so much for providing this library, it's amazing :)

I just wanted to let you know that there are a view strings missing currently. The title says "soon to be" because I am unsure weather they already are missing in the stable branch. I am using the beta branch.

Strings missing in `MaterialLocalizationsEo`:

- `MaterialLocalizations.lookUpButtonLabel`
- `MaterialLocalizations.menuDismissLabel`
- `MaterialLocalizations.searchWebButtonLabel`
- `MaterialLocalizations.shareButtonLabel`

Strings missing in `CupertinoLocalizationsEo`:

- `CupertinoLocalizations.lookUpButtonLabel`
- `CupertinoLocalizations.menuDismissLabel`
- `CupertinoLocalizations.searchWebButtonLabel`
- `CupertinoLocalizations.shareButtonLabel`

**Comment by deakjahn** [comment]
Probably not, I've just refreshed my Flutter to 3.13.8 and no warning yet. But let's be on our toes...

**Comment by florian-obernberger** [comment]
Yeah , my current (updated today) version is 3.16.0-0.4.pre

I think I'll just create a fork of it for now so it works with my project and then I guess if the translations are correct you can merge it, once the changes hit flutter stable?

**Comment by deakjahn** [comment]
Yes, sure.

**Comment by florian-obernberger** [comment]
I'm closing this as it already got released :)

**Comment by deakjahn** [comment]
Yes, I happened to be in an app that relies on it and it warned me, so I became aware of it.
